@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

LAYOUT_WITH_LEGEND()

Person(admin, "Admin User", "A user of the system that has an administrator role")
System(es, "Enterprise system", "The system that allows users consume de enterprise services")
System_Ext(s3, "AWS S3", "Amazon Simple Storage Service.")
System_Ext(db, "SQL Server", "Relational Data Base.")
System_Ext(sqs, "AWS SQS", "Amazon Simple Queue Service.")
System_Ext(wkr, "Worker", "System that resolve scheduled processes.")

Rel(admin, es, "Imports csv file to some batch process.")
Rel(es, s3, "Uploads the csv file.")
Rel(es, db, "Register new import request.")
Rel(es, sqs, "Publish message.")
Rel(wkr, sqs, "Consume message.")
Rel(wkr, db, "Update treated process.")

@enduml
